### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by jacobwgillespie** [emotion-icons/emotion-icons#1]
Hey! 👋 

This project looks awesome, I discovered it today after looking to see if `emotion-icons` was available on NPM.  I was considering creating and releasing a version of my `styled-icons` package using Emotion since I may be using Emotion in an upcoming project, but it looks like you already have created the port!

Would you be interested in collaborating on this and `styled-icons` in a more direct capacity?  I would love to make both `styled-icons` and `emotion-icons` part of an "official" set of packages.

My idea would be to create [a new GitHub organization](https://github.com/styled-icons) and move `styled-icons` into that organization.  Then refactor it into the following repositories:

* `styled-icons/packs` - a repo containing the definitions of the SVG files for all the different icon packs, shared by all the other repos
* `styled-icons/styled-icons` - the existing repo that would create React components using Styled Components, based on the definitions in `packs`
* `styled-icons/emotion-icons` - this would create React components using Emotion
* `styled-icons/website` - the website, with versions for both `styled-icons` and `emotion-icons`

It would be set up with Travis CI to build everything, so a change to the `packs` repo adding new icon packs / updating them / etc would automatically build the other repos, deploy the NPM packages, update the website, etc.

And if there were ever any other CSS-in-JS libraries or frontend frameworks to target, they could be added as additional repos and would still share the same icon pack source.

If you like this idea and want to contribute, I'd be happy to add you as a maintainer of the GitHub organization and all of the packages, so you'd be free to make improvements, etc.

Let me know what you think!

**Comment by JoshRosenstein** [comment]
@jacobwgillespie- I apologize , i have not been receiving any notifications.  Yes this does sound like a great idea since i do often switch back and forth between CSS-in-JS libraries, and would be much better if icons in both packages were in sync. Let me know if you are still interested in doing this. Thanks

**Comment by JoshRosenstein** [comment]
Was also thinking, if we create icon output configs, like i have in this lib, then we can just have different createIcon.js files that can switch between css-js libs, and preact/react (if needed).

Kinda like...
## ConfigPackage @styled-icons/shared/boxicon/Alert.js
```jsx
export const AlertConfig = {"displayName":"Alert","attrs":{"fill":"currentColor"},"css":{"display":"inline-block","verticalAlign":"middle","overflow":"hidden","maxHeight":"100%","maxWidth":"100%","margin":"auto"},"width":16,"height":16,"titleKey":"Alert-title","viewBox":"0 0 16 16","labelledby":"icon-title-Alert","body":[{"type":"path","props":{"fillRule":"evenodd","d":"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z","key":"k0"}}]}

```
## EmotionReact @styled-icons/emotion/boxicon/Alert.js
```jsx
import Alert from '@styled-icons/shared/boxicon/Alert'
import createReactEmotionIcon from '../createReactEmotionIcon'

export default createReactEmotionIcon(Alert)
```

## StyledReact @styled-icons/styled/boxicon/Alert.js
```jsx
import Alert from '@styled-icons/shared/boxicon/Alert'
import createReactStyledIcon from '../createReactStyledIcon'

export default createReactStyledIcon(Alert)
```

## EmotionPreact @styled-icons/preact-emotion/boxicon/Alert.js
```jsx
import Alert from '@styled-icons/shared/boxicon/Alert'
import createPreactEmotionIcon from '../createPreactEmotionIcon'


export default createPreactEmotionIcon(Alert)
```

**Comment by JoshRosenstein** [comment]
Until i can get connected with @jacobwgillespie- I think i will transfer this repo into its own org to allow more maintainers

**Comment by jacobwgillespie** [comment]
Hey!  So sorry, just found this - looks like GitHub isn't tagging me thanks to the dash in the @-mention.

I'm still definitely interested in teaming up - I can set up an org for this.  For the name, do you prefer @styled-icons or @icon-kit or something else?  I'm on the fence about the name I'd prefer - I like @styled-icons since it reflects generally what the package is for, and I like @icon-kit since it's more generic, and there may be usefulness for the package with the icon definitions outside of Styled Components / React.

My email address is jacobwgillespie@gmail.com in case you need to or want to get in touch that way.

**Comment by jacobwgillespie** [comment]
Works for me, I sent you an invite to @icon-kit

**Comment by meritozh** [comment]
Any news on this? I wanted to try emotion and styled-icons, but I don't want install two css-in-js library... Or is there anything I can help with this?

**Comment by jacobwgillespie** [comment]
@JoshRosenstein following up on this (it's been a while!):

I've just recently completed a tooling upgrade for Styled Icons that automates a lot of the building / publishing flow, especially in response to upstream icon pack updates. To that end, the icon SVG sources live at https://github.com/svg-icons/svg-icons and Styled Icons now lives at https://github.com/styled-icons/styled-icons.

Would you be interested in migrating `emotion-icons` to https://github.com/emotion-icons? I would be happy to take over maintenance of the library using the same framework I've built for Styled Icons, just using Emotion instead of Styled Components.

If that would be of interest, I believe the steps would be:

1. I would add you to the https://github.com/emotion-icons organization
2. You would transfer this repo into the new organization - this would preserve any links to this repo via GitHub redirects
3. You would add me and @icon-bot as maintainers of the `emotion-icons` package on npm via:

    ```
    npm owner add jacobwgillespie emotion-icons
    npm owner add icon-bot emotion-icons
    ```

4. I would push a new version of the repo code, based on the latest version of `styled-icons`, and configure CI to automatically build / publish to npm

Let me know if you have any thoughts / ideas / questions!

**Comment by JoshRosenstein** [comment]
@jacobwgillespie  haha yes it has been awhile, unfortunately a new job has pulled me away from contributing/maintaining much of anything. Looks like you've implemented everything you originally visioned wonderfully! I'd be happy to transfer it all over.

Again, great work !

**Comment by jacobwgillespie** [comment]
Awesome! 🎉 I've invited you to the @emotion-icons org, you should have received an email or can also accept the invite directly at https://github.com/emotion-icons.

**Comment by JoshRosenstein** [comment]
Should be all set!

**Comment by jacobwgillespie** [comment]
Awesome, thank you! 🚀

**Comment by jacobwgillespie** [comment]
Version 2 of `emotion-icons` has been released! 🎉 Thanks again @JoshRosenstein ❤️
