### ISSUE TITLE
How to make an icon focusable?

### ISSUE THREAD

**Issue by Vanals** [emotion-icons/emotion-icons#119]
Hi,

I saw that by default the SVG elements have the property focusable set to false. Reading the documentation I haven't seen property to achieve that.

Is there any way to set the focusable HTML property to true? If not is there any reason?

<img width="699" alt="Screenshot 2020-09-10 at 16 22 50" src="https://user-images.githubusercontent.com/25549355/92753531-e239f000-f381-11ea-8c75-ca4212a9abc4.png">

Thank you.

**Comment by jacobwgillespie** [comment]
Hey! The default is to set the `focusable` prop to `false`, but it should be possible to override this yourself, like so:

```javascript
import {Alert} from '@emotion-icons/octicons'

<Alert focusable="true" />
```

That should override the value. That said, I believe `focusable` only applies to Internet Explorer and some older versions of Edge and is there to work around the fact that most browsers don't consider SVGs focusable, but older IE did. You may instead want to wrap the icon in another element like a div or span and make that a focus target.

For extra details, see https://allyjs.io/tutorials/focusing-in-svg.html

**Comment by Vanals** [comment]
> Hey! The default is to set the `focusable` prop to `false`, but it should be possible to override this yourself, like so:
> 
> ```js
> import {Alert} from '@emotion-icons/octicons'
> 
> <Alert focusable="true" />
> ```
> 
> That should override the value. That said, I believe `focusable` only applies to Internet Explorer and some older versions of Edge and is there to work around the fact that most browsers don't consider SVGs focusable, but older IE did. You may instead want to wrap the icon in another element like a div or span and make that a focus target.
> 
> For extra details, see https://allyjs.io/tutorials/focusing-in-svg.html

Thank you for your reply Jacob! 

i tried to pass focusable="true" but nothing changes. 
It should be possible to make and SVG focusable/tabbable. If I set tabindex='0' it is possible tab the icon! But as far as I know, reading the documentation, that's not a value I can directly set on the svg! :/  I wonder why

**Comment by Vanals** [comment]
Thank you, Jacob! It works. Was my fault not speaking the props. As I was using a HOC.
