### ISSUE TITLE
Not support yet for @emotion 11 version

### ISSUE THREAD

**Issue by donghoon-song** [emotion-icons/emotion-icons#216]
Hello. I was just accidentally using @emotion 11 version and it was the latest released just 14 days ago.

When I tried to use your package, I encountered the issue saying `Can't resolve '@emotion/styled-base'`.
I think this is related to the pr below.
https://github.com/emotion-js/emotion/pull/1575
`@emotion/styled-base` was moved to `@emotion/styled/base`.

I don't know how to support it so I just want to how contributors will deal with this issue by watching :) Thanks for reading

**Comment by prabhuignoto** [comment]
recently upgraded to emotion 11 and hit the exact same issue.  can we have this fixed please.

thanks

**Comment by jacobwgillespie** [comment]
This has been released as v3.0.0 - thanks @JoshRosenstein! 🎉
